# Palette baseada na logo do NixOS (Fundo Grafite com Autosuggest do Fish ajustado)

# Cores de Fundo, Texto e Cursor
background            #2E323A
foreground            #EDF2F7
cursor                #8FCBF5
selection_background  #5277C3
selection_foreground  #2E323A

# Cores Normais (Normal Colors)
color0  #2E323A
color1  #DB7A85
color2  #7BC090
color3  #E4C98A
color4  #5277C3
color5  #BA96CE
color6  #7EBAE4
color7  #EDF2F7

# Cores Brilhantes (Bright Colors)
color8  #6C7485  # <-- Esta cor controla o texto de sugestão/completar do Fish
color9  #E6919A
color10 #93CFA6
color11 #ECD7A2
color12 #6A8ED9
color13 #C9A8DB
color14 #9CD5FA
color15 #FFFFFF
